### ISSUE TITLE
Upgrade README file

### ISSUE THREAD

**Issue by Jamiewarb** [debatsi/MVP#1]
The README needs some updating to be fully featured

**Comment by Jamiewarb** [comment]
![image](https://user-images.githubusercontent.com/2754728/46287974-3de78600-c57c-11e8-81eb-68828e22ab68.png)

**Comment by debatsi** [comment]
Read, agreed, implemented.

**Comment by Jamiewarb** [comment]
Just so you know, there are some outstanding pull-requests. One of which is a README file I've created. Another is a new file FEATURES.md, which takes your existing README and puts it in that file.
